### ISSUE TITLE
each member spin up a barebones streamlit/solara app

### ISSUE THREAD

**Issue by klassagne** [oceanhackweek/ohw24_proj_HAB_FE_us#1]
We are planning on each spinning up an app so we can 1) learn how to do it and 2) work independently on components and drop them into a final version as we go
Streamlit [App](https://docs.streamlit.io/get-started/tutorials/create-an-app)
[Solara App](https://github.com/oceanhackweek/ohw24_proj_HAB_FE_us)

**Comment by Adelle-Pitsas** [comment]
We've decided on streamlit! We are spinning up a streamlit app and tracking changes via branches and PR
